{% set name = "flake8-multiline-containers" %}
{% set version = "0.0.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8-multiline-containers-{{ version }}.tar.gz
  sha256: 7c47527f1a2b0a991b876e58a2758e0ecc6b2d10a5fd4ee7740d042722f2f281

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - attrs >=19.3.0
    - flake8 >=3.7.9
    - python >={{ python_min }}

test:
  imports:
    - flake8_multiline_containers
  commands:
    - pip check
    - flake8 --version | grep flake8-multiline-containers
  requires:
    - flake8
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jsfehler/flake8-multiline-containers
  summary: Ensure a consistent format for multiline containers.
  license: MIT
  # PR made upstream to package in license file: https://github.com/jsfehler/flake8-multiline-containers/pull/108
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
